### PR TITLE
Added an image to StudentImages folder

### PR DESCRIPTION
**Pull request by tclonts**

### CODE REVIEW

**Comment by armadsen** [comment]
Ha, I was going to message you and say that one of my students knows you, @BryanJBryce.

**Comment by BryanJBryce** [comment]
@tclonts Woah! What's up man?!

**Comment by BryanJBryce** [comment]
@armadsen We played on the tennis team together in high school...I was always fighting to stay on varsity and he was always #1 from he time he was a freshman pretty much. I also had a crush on his sister 😄

**Comment by tclonts** [comment]
@BryanJBryce Hey man long time no see!

**Pull request merged**
